cloudinary/cloudinary_gem

- lib/cloudinary/missing.rb
This PR enables root path for shared CDN.
It includes the functional change and the related tests.
> Allow root path for shared CDN

- lib/cloudinary/carrier_wave/process.rb
Fix ambiguous splat operator by parenthesizing the argument
> Fix ambiguous splat operator

- lib/cloudinary/migrator.rb
Removed a useless assignment to local variable `result` inside the `#update_row` method
> Removed a useless assignment to variable

- lib/cloudinary/utils.rb
- spec/utils_spec.rb
Added support for authenticated images + test
> support URL SEO suffix with additional resource types

- lib/cloudinary/auth_token.rb
- lib/cloudinary/migrator.rb
- lib/cloudinary/utils.rb
- spec/auth_token_spec.rb
This PR should not merge to master until the respective functionality is deployed to production.
> Add `access_control` parameter to `upload` and `update` 

- lib/cloudinary/carrier_wave.rb
- lib/cloudinary/migrator.rb
> Fix carrierwave deps & output

- samples/photo_album/app/uploaders/image_uploader.rb
👋 Hi there!
The previous link goes to the general Cloudinary Rails documentation. The new one goes specifically to the CarrierWave integration, as originally intended.
Cheers :)
> Update link to CarrierWave integration

- lib/active_storage/service/cloudinary_service.rb
- spec/active_storage/service/cloudinary_service_spec.rb
- spec/active_storage/service/configurations.yml
> Add support of global folder in ActiveStorage

- lib/cloudinary/uploader.rb
- spec/uploader_spec.rb
> Allow setting uploader timeout to `nil`

- lib/cloudinary/utils.rb
- spec/utils_spec.rb
> Fix handling of empty value in `if` parameter

- lib/cloudinary/carrier_wave/remote.rb
> Fix `download` function in `Cloudinary::CarrierWave` module

- spec/uploader_spec.rb
> Fix detection integration test

- lib/cloudinary/video_helper.rb
- spec/video_tag_spec.rb
(Update video HTML 5 tag to include support for h265 and vp9)
> Added support for sources in video tag

- cloudinary.gemspec
- spec/archive_spec.rb
[x] Gihtub issue (Add reference - #XX)
[ ] Bug fix
[x] Yes
[ ] No
> Bump vulnerable version of rubyzip

- cloudinary.gemspec
> Fix `cloudinary.gemspec` glob issue

- lib/cloudinary/uploader.rb
- spec/uploader_spec.rb
Add possibility to overwrite original filename when uploading
[ ] Bug fix
[x] Yes
[ ] No
> Add upload param 'filename_override'

- spec/utils_spec.rb
Allow context metadata to be a variable
[ ] Bug fix
[x] Adds more tests
> Add test for context metadata as user variables

- lib/cloudinary/api.rb
- lib/cloudinary/utils.rb
- spec/api_spec.rb
- spec/archive_spec.rb
Adds possibility to restore specific version of backup for asset. Also adds possibility to retrieve backup versions with uploaded asset.
[ ] Bug fix
[x] Yes
[ ] No
> Add support for download backup version API

- lib/cloudinary/api.rb
- spec/api_spec.rb
> Return structured metadata in resources apis

- lib/cloudinary/api.rb
- spec/api_spec.rb
> Add live parameter support when creating and updating upload presets

- lib/cloudinary/api.rb
- spec/metadata_spec.rb
Add possibility to sort by metadata field. Only value is supported now
[ ] Bug fix
[x] Yes
[ ] No
> Add sort by metadata field

- lib/cloudinary/uploader.rb
- spec/uploader_spec.rb
> Return context and structured metadata in rename API

- spec/api_spec.rb
- spec/spec_helper.rb
- spec/uploader_spec.rb
> Refactor metadata usage in tests

- lib/cloudinary/account_api.rb
- spec/account_api_spec.rb
> Implement missing tests

- lib/cloudinary/search.rb
- spec/search_spec.rb
> Remove duplicates in Search Api fields

- lib/cloudinary/uploader.rb
- spec/uploader_spec.rb
> Add support for `create_slideshow` Upload API

- cloudinary.gemspec
- spec/utils_spec.rb
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
Updates `.gemspec` file and spec file to support Ruby 3.0.
Closes #468
Merge #467 in advance.
- [n/a] My change requires a change to the documentation.
> Support for Ruby 3.0

- lib/cloudinary/api.rb
[x] Refactoring
[ ] Bug fix
[ ] Yes
[x] No
> Add missing docstrings for Admin API methods

- lib/cloudinary/auth_token.rb
- spec/auth_token_spec.rb
> Ignore URL in AuthToken generation if ACL is provided

- spec/utils_spec.rb
> Add tests for expression normalization

- lib/cloudinary/uploader.rb
- spec/uploader_spec.rb
This PR adds tests to https://github.com/cloudinary/cloudinary_gem/pull/479
> Add support for Dynamic Folder upload parameters

- lib/cloudinary/api.rb
- spec/api_spec.rb
> Add support for `assetsByAssetIds` Admin API

- lib/cloudinary/api.rb
- spec/metadata_spec.rb
> Add API for sorting metadata fields

- lib/cloudinary/auth_token.rb
- spec/auth_token_spec.rb
> Support multiple acls in cookies

- lib/cloudinary/base_api.rb
- spec/api_spec.rb
> Fix support of the lowercase response headers

- lib/cloudinary/utils.rb
- spec/video_url_spec.rb
> Allow to disable b-frames for video codec

- lib/cloudinary/api.rb
- spec/api_spec.rb
> Add support for `metadata` in `update` Admin API

- lib/cloudinary/api.rb
- spec/api_spec.rb
> Add support for `resources_by_asset_folder` for Admin API

- lib/cloudinary/api.rb
- lib/cloudinary/uploader.rb
- spec/api_spec.rb
- spec/uploader_spec.rb
> Add support for `clear_invalid` metadata parameter

- lib/active_storage/service/cloudinary_service.rb
- spec/active_storage/service/cloudinary_service_spec.rb
> Fix Active Storage resource type for direct uploads

- .travis.yml
- spec/api_spec.rb
> Fix travis configuration and failing unit tests

- cloudinary.gemspec
> Fix failing tests dependencies

- lib/active_storage/service/cloudinary_service.rb
- lib/cloudinary/uploader.rb
- spec/active_storage/database/setup.rb
- spec/active_storage/service/cloudinary_service_spec.rb
- spec/uploader_spec.rb
> Add support for large files in active storage

- lib/cloudinary/api.rb
- spec/metadata_rules_spec.rb
> Add support for Conditional Metadata Rules API

- lib/cloudinary/utils.rb
- spec/utils_spec.rb
> Support start offset and end offset in variable materialization

- lib/cloudinary/api.rb
- spec/api_spec.rb
> Add support for related assets Admin APIs

- lib/cloudinary/api.rb
- lib/cloudinary/uploader.rb
- spec/utils_spec.rb
> Add support for `media_metadata` API parameter

- lib/cloudinary.rb
- lib/cloudinary/search.rb
- lib/cloudinary/search_folders.rb
- spec/search_folders_spec.rb
- spec/search_spec.rb
> Add support for `SearchFolders` API

- lib/cloudinary/search.rb
- lib/cloudinary/utils.rb
- spec/search_spec.rb
> Add support for Search URL

- lib/cloudinary/api.rb
- lib/cloudinary/uploader.rb
- spec/api_spec.rb
- spec/utils_spec.rb
> Add support for `visual_search` Admin API

- lib/cloudinary/uploader.rb
- spec/api_spec.rb
- spec/spec_helper.rb
- spec/uploader_spec.rb
> Add support for `on_success` upload parameter

- lib/cloudinary/api.rb
- lib/cloudinary/uploader.rb
- lib/cloudinary/utils.rb
- spec/api_spec.rb
> Add support for `image_file` parameter in `visual_search` Admin API

- lib/cloudinary/account_api.rb
- spec/account_api_spec.rb
> Add support for access keys management in Account Provisioning API

- lib/cloudinary/api.rb
- lib/cloudinary/search.rb
- spec/api_spec.rb
- spec/search_spec.rb
> Add support for `fields` parameter in Search and Admin APIs

- lib/cloudinary/utils.rb
- lib/cloudinary/video_helper.rb
- spec/video_tag_spec.rb
> Add support for `use_fetch_format` parameter in `cl_video_tag`

- README.md
Cloudinary support confirmed to me that Rails 7 is supported. Thank you!
> Add Rails 7.x to supported versions on README.md

- .travis.yml
- cloudinary.gemspec
> Fix `sqlite3` dependency version

- lib/cloudinary/account_api.rb
- lib/cloudinary/api.rb
- lib/cloudinary/utils.rb
- spec/api_spec.rb
> Add support for `analyze` API

- lib/cloudinary.rb
- lib/cloudinary/analytics.rb
- lib/cloudinary/utils.rb
- spec/active_storage/service/cloudinary_service_spec.rb
- spec/analytics_spec.rb
- spec/auth_token_spec.rb
- spec/cloudinary_helper_spec.rb
- spec/image_spec.rb
- spec/rake_spec.rb
- spec/utils_spec.rb
- spec/video_tag_spec.rb
- spec/video_url_spec.rb
> Add support for URL Analytics

- cloudinary.gemspec
- lib/active_storage/service/cloudinary_service.rb
- lib/cloudinary.rb
- lib/cloudinary/carrier_wave.rb
- lib/cloudinary/helper.rb
- lib/cloudinary/uploader.rb
- lib/cloudinary/utils.rb
- spec/utils_spec.rb
* `Cloudinary::Utils.unsigned_download_url`
* `Cloudinary::Utils.signed_download_url`
* `Cloudinary::Utils.zip_download_url`
* `cl_zip_download_url`
> Remove deprecated methods

- cloudinary.gemspec
> Fix rake tasks

- lib/active_storage/service/cloudinary_service.rb
- spec/active_storage/service/cloudinary_service_spec.rb
> Fix `fetch` url generation with Active Storage `folder` configuration

- lib/cloudinary/utils.rb
- spec/utils_methods_spec.rb
> Fix detection of base64 encoded files with complex MIME type

- lib/cloudinary/api.rb
- spec/api_spec.rb
> Add support for `rename_folder` Admin API

- lib/active_storage/service/cloudinary_service.rb
> Fix asset type detection in ActiveStorage

- lib/cloudinary/api.rb
- spec/api_spec.rb
> Add support for `config` Admin API

- lib/cloudinary/base_api.rb
> Add support for `429 Too Many Requests` HTTP status code

- lib/cloudinary/utils.rb
- spec/utils_spec.rb
> Fix API parameters signature

- lib/cloudinary/cloudinary_controller.rb
- lib/cloudinary/preloaded_file.rb
- lib/cloudinary/uploader.rb
- lib/cloudinary/utils.rb
- spec/carriewave_spec.rb
- spec/uploader_spec.rb
- spec/utils_spec.rb
> Fix response signature verification
