cloudinary/cloudinary_gem

- lib/cloudinary/helper.rb
- spec/cloudinary_helper_spec.rb
- spec/spec_helper.rb
This PR removes unvalid </img> tags
There is a bug in the current version of the Cloudinary gem that occurs when using `dpr` or `responsive` options with the cloudinary image tag helper
```
<%= cl_image_tag 'sample.jpg', dpr: :auto %>
```
outputs
```
```
Images are self closing, and the use of [tag](http://apidock.com/rails/ActionView/Helpers/TagHelper/tag) instead of [content_tag](http://apidock.com/rails/ActionView/Helpers/TagHelper/content_tag) fixes that.
> Fix image closing tags

- README.md
`Gemfile` and `environment.rb` have no shell prompt.
> Remove prompts in ruby file.

- lib/cloudinary/uploader.rb
Former code returned either 0 or nil because ~= returns the number of matches.
Moreover, the conversion to string is not necessary.
> exists? must return booleans

- lib/tasks/cloudinary.rake
Ensuring rails environment is loaded as a dependency of running sync_static rake task, so anything initializer that sets up Cloudinary.config takes affect.
This will increase the time it takes for the rake task to load, but is not the end of the world to allow proper configuration to be loaded.
> Fix: sync_static doesn't pick up configuration from initializers

- lib/cloudinary/carrier_wave/remote.rb
The newer carrierwave signature for `download!` looks like this:
```
def download!(uri, remote_headers = {})
```
This updates cloudinary to accept the param without using it since it doesn't appear necessary.
> update download method signature to match newest carrierwave

- lib/cloudinary/utils.rb
- spec/utils_spec.rb
Fixed regex to exclude simple negative numbers when replacing "-" (minus sign) with "sub" operator + test
> don't normalize negative numbers

- lib/cloudinary/api.rb
- spec/api_spec.rb
I ran into this in a Rails project. I wanted to call `#slice` on the Response.
I was using the Admin API and making a single resource call.
I've replaced the public_id with 'foo'.
```
response = Cloudinary::Api.resource "foo"
=> { "public_id" => 'foo', ...  }
response.is_a? Hash
=> true
response.respond_to? :slice
=> true
response.slice 'public_id'
=> ArgumentError: wrong number of arguments (given 0, expected 1)
from /Users/mattsullivan/.rvm/gems/ruby-2.3.4/gems/cloudinary-1.8.1/lib/cloudinary/api.rb:16:in `initialize'
from /Users/mattsullivan/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/core_ext/hash/slice.rb:23:in `new'
from /Users/mattsullivan/.rvm/gems/ruby-2.3.4/gems/activesupport-4.2.10/lib/active_support/core_ext/hash/slice.rb:23:in `slice'
```
The response …
> Fix the overwritten initializer for hash

- lib/tasks/cloudinary.rake
This got lost in the addition of syncing non-image assets. Adding back so rails environment is loaded as a dependency.
> load environment when running sync_static task

- lib/cloudinary/carrier_wave/storage.rb
- spec/storage_spec.rb
Neo4j.rb doesn't implement the `set` method, which results in a
`NoMethodError` when using Carrierwave with a Neo4j enhanced model.
`write_attribute` does exist and seems the most appropriate choice for
ensuring the value of the uploaded file gets persisted.
> Use the correct method for updating a column

- lib/cloudinary.rb
- lib/cloudinary/cloudinary_controller.rb
Fix #146, added namespace resolution for cloudinary controller for avoiding conflicts when generating a controller with same name.
> namespace resolution for cloudinary controller for avoiding conflicts

- lib/cloudinary/utils.rb
A fix for #329 
AFAIK NIL == nil in all versions of ruby, so there should be no downside. The deprecation warning is
```
lib/cloudinary/utils.rb:1074: warning: constant ::NIL is deprecated
```
Let me know if there is anything I can do to help get this merged.
> Fix ruby 2.4 deprecation warning

- lib/cloudinary/utils.rb
close #280 
`jpeg` was removed by [this commit](https://github.com/cloudinary/cloudinary_gem/commit/65b79c87f0bc2f33fb0c25f8a54d5c67faf8d223) .  
If you have a reason to remove `jpeg`,  please tell me why `jpeg` is removed. ( @diazruy [has already asked same question](https://github.com/cloudinary/cloudinary_gem/commit/65b79c87f0bc2f33fb0c25f8a54d5c67faf8d223#r26772859), but nobody answered it.
Thanks.
> Add jpeg to IMAGE_FORMATS

- lib/cloudinary/api.rb
- spec/api_spec.rb
Updated old PR that had failing build and was abandoned
> Adding support for derived_next_cursor to options when listing details of single resource

- samples/photo_album/Gemfile
ActiveRecord SQLite3 adapter version 3.2 requires requires sqlite3 '~>1.3.5'.
> Limit sqlite3 to a compatible version

- lib/active_storage/service/cloudinary_service.rb
There is an error when I upload image to Cloudinary after I set `Cloudinary.config.secure = true` for https url. It is because when ActiveStorage trying to run `ActiveStorage::AnalyzeJob`, it will stream the image from Cloudinary without setting ssl to true.
```2019-11-14T06:52:03.421Z pid=34001 tid=ow0hcp7xh WARN: Errno::ECONNRESET: Connection reset by peer
2019-11-14T06:52:03.421Z pid=34001 tid=ow0hcp7xh WARN: <internal:prelude>:73:in `__read_nonblock'
<internal:prelude>:73:in `read_nonblock'
/Users/hjchan/.rbenv/versions/2.6.0/lib/ruby/2.6.0/net/protocol.rb:210:in `rbuf_fill'
/Users/hjchan/.rbenv/versions/2.6.0/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
/Users/hjchan/.rbenv/versions/2.6.0/lib/ruby/2.6.0/net/protocol.rb:201:in `readline' …
```
> Fix active storage download not using ssl for https

- lib/active_storage/service/cloudinary_service.rb
Would be nice if the `folder` option will be not required when we use Active Storage. Or is it a bad idea?
> Make global folder optional in Active Storage

- lib/cloudinary/cloudinary_controller.rb
- lib/cloudinary/railtie.rb
As originally raised in #351, Cloudinary's gem produces deprecation warning for autoloading during initialization. Unfortunately, those warnings are still lingering and will be outright errors in future releases of Rails.
I have [this sample app that reproduces the warnings](https://github.com/wspurgin/vanilla) if you run `rake spec`, you'll see:
```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.
Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't …
```
> Fix lingering Rails 6 autoload warnings

- lib/cloudinary/carrier_wave.rb
- samples/photo_album/config/initializers/carrierwave.rb
> Set default cache storage to `file` in `CarrierWave`

- lib/cloudinary/utils.rb
- spec/utils_spec.rb
`normalize_expression()` will no longer transform predefined variables into their shortened form if they are preceded by an ampersand (meaning they are variables).
For example: `$width` will not be transformed into `$w`.
> When normalizing expressions, don't replace variables named liked a predefined variable

- .travis.yml
- cloudinary.gemspec
- spec/api_spec.rb
- spec/search_spec.rb
- spec/spec_helper.rb
- tools/allocate_test_cloud.sh
- tools/get_test_cloud.sh
- tools/update_version
This PR integrates with sub-account test service which allocates clean sub-accounts for travis tests.
It also solves some race conditions in integration tests, by retrying failed integration tests.
By default there are 3 retries with a timeout of 3 seconds between tries.
update_version script is aligned with other SDKs as well.
> Integrate with sub-account test service

- lib/cloudinary/helper.rb
SassC options are parsed as a hash with string keys, while `cloudinary_url` uses symbols.
This causes an issue: `:type` cannot be overridden from sass, since we get: `{:type => :asset, "type" => "upload"}`
This PR normalises all keys to symbols.
[x] Bug fix
[ ] Yes
[x] No
> Fix options handling issue in SassC

- lib/cloudinary/api.rb
- lib/cloudinary/uploader.rb
- spec/metadata_spec.rb
- spec/spec_helper.rb
- spec/uploader_spec.rb
Adds full support for defining, maintaining, and using structured metadata with the Admin and Upload APIs.
-  New feature
- Adds more tests
> Add structured metadata to Admin and Upload API

- lib/active_storage/service/cloudinary_service.rb
- spec/active_storage/service/cloudinary_service_spec.rb
ActiveStorage integration was not reusing `url` function in the `download` which led to inconsistency. The issue arose with raw files that have a file extension. When uploading a raw file to cloudinary, the public id ends up in a form: public_id.original_extension (since raw files are not transformable), as opposed to images/videos, where public_id is a base name without extension. So, in order to download the file we need to provide both public_id (which is the active storage key) and a file extension that we have from the blob key metadata. 
This PR fixes the inconsistency.
[x] Bug fix
[x] Yes
[ ] No
Fixes #420
> Fix download of a raw file in ActiveStorage

- lib/cloudinary/utils.rb
- spec/archive_spec.rb
- spec/utils_spec.rb
Add a new method in the Upload API - `download_folder`.
This method creates and returns a URL that when invoked creates an archive of a folder.
> Add download_folder method

- spec/spec_helper.rb
- spec/uploader_spec.rb
The test for `eval` has a bug that causes it to leave leftover images that aren't deleted during test teardown.
This happens because the current eval test overwrites the tags of the uploaded image, including the tag used in the teardown to delete it.
This PR changes the eval string to test how it does something other than changing tags.
> Change test for `eval` upload parameter

- spec/helper_spec.rb
- spec/spec_helper.rb
- spec/support/addon_type.rb
- spec/support/helpers/integration_test_case_helper.rb
- spec/uploader_spec.rb
Added `should_test_addon()` which can be used to determine whether a certain addon should be tested and allow skipping those that shouldn't.
To enable certain addon testing, add its id to the `CLD_TEST_ADDONS` environment variable. Alternatively set `CLD_TEST_ADDONS` to `all` to test all add ons.
This can be used in a test spec like so:
```ruby
it "should support requesting ocr analysis", should_test_addon: Helpers::AddonType::ADDON_OCR do
expect(something).to be(something)
end
```
Alternatively, it can be used inside a test's code to skip some of it. For example:
```ruby
if Helpers::IntegrationTestCaseHelper.should_test_addon(Helpers::AddonType::ADDON_WEBPURIFY
end
```
Consider adding `CLD_TEST_ADDONS=all` to Travis.
> Added helper function to ensure add on tests do not run by default

- lib/active_storage/service/cloudinary_service.rb
- spec/active_storage/service/cloudinary_service_spec.rb
Provide file format for direct upload of raw files, since js client does not include original file name.
When the file is uploaded from the server, the request includes original filename. That allows Cloudinary
to identify file extension and append it to the public id of the file (raw files include file extension
in their public id, opposed to transformable assets (images/video) that use only base name). When uploading
through direct upload (client side js), filename is missing, and that leads to inconsistent/broken URLs.
To avoid that, we explicitly pass file format in options.
[x] Bug fix
[x] Yes
[ ] No
> Fix direct upload of raw files

- lib/cloudinary/uploader.rb
- lib/cloudinary/utils.rb
- spec/utils_spec.rb
Add possibility to choose SHA-256 hashing algorithm when signing urls and requests.
[ ] Bug fix
[x] Yes
[ ] No
> Add support of SHA-256 algorithm in calculation of auth signatures

- lib/cloudinary/utils.rb
- spec/expression_normalization_spec.rb
- spec/utils_spec.rb
User-defined variables which contain a string that matches a predefined variable (but does not start with that string) should not be affected when normalized.
For example $myheight_100 should not be normalized to $myh_100 but remain $myheight_100.
This PR fixes this and other similar cases.
[x] Bug fix
[x] Yes
[ ] No
> Complex expressions now produce correct results

- lib/cloudinary/auth_token.rb
- spec/auth_token_spec.rb
Enforce AuthToken to have either acl or urls on new token generation
[x] Bug fix
[x] Yes
[ ] No
> Add validation to auth token generation to enforce url or acl in the object

- lib/active_storage/service/cloudinary_service.rb
- spec/active_storage/service/configurations.yml
If the service was created with a type parameter other than `upload`, then the deletion does not work.
I added a fix, the tests were not included, since the test file uses 1 service instance(https://github.com/cloudinary/cloudinary_gem/blob/master/spec/active_storage/service/cloudinary_service_spec.rb#L19) with static parameters, I don’t know if it is necessary to create another service additional with a different configuration for tests.
[x] Bug fix
[ ] Yes
[x] No
https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/uploader.rb#L145 (by default `upload`)
https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/api.rb#L70
> Fix service delete and exist methods

- lib/cloudinary/uploader.rb
- lib/cloudinary/utils.rb
- spec/spec_helper.rb
- spec/uploader_spec.rb
- spec/utils_spec.rb
Add support for urls list as source for sprites and multi.
[ ] Bug fix
[x] Yes
[ ] No
> Allow 'multi' and 'sprite' with urls, add 'download_generated_sprite' and 'download_multi' methods

- lib/cloudinary/api.rb
- spec/api_spec.rb
The transformation definition is now passed in body of request instead of as a part of query string
[x] Refactoring
[ ] Bug fix
[x] Yes
[ ] No
> Pass transformation in request body rather than in query param

- README.md
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
Updates a link for Travis CI.
- Old: https://travis-ci.org/github/cloudinary/cloudinary_gem
- New: https://app.travis-ci.com/github/cloudinary/cloudinary_gem
TRAVIS CI, GMBH shut down `travis-ci.org`.
- [n/a] GitHub issue (Add reference - #XX)
- [n/a] Refactoring
- [n/a] New feature
- [n/a] Bug fix
- [n/a] Adds more tests
- [n/a] Yes
- [n/a] No
n/a
- [n/a] My code follows the code style of this project.
- [n/a] My change requires a change to the documentation.
- [n/a] I ran the full test suite before pushing the changes and all the tests pass.
> Update link to new Travis-CI.com

- .travis.yml
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
Add current Ruby versions 2.6, 2.7, and 3.0 (with allow_failure) for testing.
Actual fix to support Ruby 3.0 is deferred in #468. Merge this first and then move to it.
> Add current Ruby version for testing

- lib/cloudinary.rb
- spec/config_spec.rb
- spec/data/cloudinary.yml
The goal of this PR is to have YAML aliases supported for the config file in Ruby 3.1
By default, Ruby 3.1 will use `safe_load` so we have to explicitly allow aliases
cf
> Psych 4.0 changes `Psych.load` as `safe_load` by the default. You may need to use Psych 3.3.2 for migrating to this behavior. [[Bug #17866](https://bugs.ruby-lang.org/issues/17866)]
in https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/
For example in our project, the `config/cloudinary.yml` file looks like
```yaml
---
default: &default
api_key: '<%= ENV['CLOUDINARY_API_KEY'] %>'
api_secret: '<%= ENV['CLOUDINARY_API_SECRET'] %>'
staging: &staging
<<: *default
cloud_name: our_test_cloud
development: *staging
test: *staging
production:
<<: *default
cloud_name: our_prod_cloud
```
and it's not supported by the …
> Configuration: use YAML.safe_load and allowing aliases (for Ruby 3.1)

- lib/cloudinary/carrier_wave/process.rb
- spec/carriewave.rb
Try to fix the problem, that `model.image.file` will be nil even if the file is uploaded.
Calling `retrieve_from_store!` after `store!` called can populate `@file` and `@identifier` variable.
So that will fix this problem.
> Retrieve file after store

- lib/cloudinary/utils.rb
- spec/utils_spec.rb
> Fix escaping of special characters in `public_id`

- lib/active_storage/service/cloudinary_service.rb
- spec/active_storage/service/cloudinary_service_spec.rb
Fixes #506
This PR fixes issue when raw files with file extension are not deleted, since public id is missing the file extension.
> Fix Active Storage Service public id of the raw asset handling

- lib/cloudinary/carrier_wave/storage.rb
Using update_all is incompatible with [optimistic locking](https://api.rubyonrails.org/classes/ActiveRecord/Locking/Optimistic.html) and if you attempt to make further updates to the record it fails with ActiveRecord::StaleObjectError
Something like:
```ruby
person = Person.find(1)
person.update!(avatar: '...file...')
person.update!(name: 'Oliver') # this will throw a ActiveRecord::StaleObjectError error
```
> replace update_all to update_column

- lib/cloudinary/railtie.rb
The injection of the CloudinaryHelper module can happen lazily when ActionView::Base is loaded by some other code needing it, and there is no reason to trigger the loading early in the railtie.
A consequence of this change is that you can avoid the loading of ActionView::Base altogether in some cases, e.g. if running a specific test that does not need it, or when opening a rails console.
This aligns the behavior with the loading of `Cloudinary::CloudinaryController` which happens lazily too (see [railtie.rb](https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/railtie.rb#L9-L11)).
> Avoid early loading of ActionView::Base

- lib/active_storage/service/cloudinary_service.rb
- spec/active_storage/service/cloudinary_service_spec.rb
Cloudinary has support for [contextual metadata](https://cloudinary.com/documentation/contextual_metadata) but it doesn't appear to be supported as an option during `ActiveStorage::Service#url_for_direct_upload`. 
I want to send additional context to cloudinary when I generate the URL for direct upload, using active storage.
Example:
```
object.service.url_for_direct_upload(
object.key,
...,
extra_context: { company: "Rando Co." }
)
```
Creates this on cloudinary:
- I picked the `extra_context` key so it wouldn't collide with anything that I might have overlooked. We might be able to just use `context` with a `reverse_merge` of the active storage key and remove the `extra_context` option/key
- Rails 7 has support for [custom_metadata](https://github.com/rails/rails/pull/43294) via a …
> Include contextual metadata when using url_for_direct_upload

- lib/cloudinary/carrier_wave/storage.rb
Can be done by setting `upload_chunked?` to `true` in the uploader.
> Support chunked uploads with CarrierWave

- lib/cloudinary/carrier_wave/storage.rb
This broke for us upgrading to cloudinary v2 i assume this was a legacy setting
> upload_chunked? is removed

- lib/cloudinary/helper.rb
This update replaces the deprecated and removed `File.exists?` method with `File.exist?` to ensure compatibility with Ruby 3.2.0 and later versions, where the old method has been entirely removed.
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
I am not sure the function `cl_sprite_url` is still in use.
> Replace removed File.exists? with File.exist? for Ruby 3.2.0 compatibility

- lib/cloudinary/account_api.rb
- spec/account_api_spec.rb
> Add support for `delete_access_key` in Provisioning API

- cloudinary.gemspec
Adds `changelog_uri` to gemspec.
Supported here: https://guides.rubygems.org/specification-reference/#metadata Useful for running https://github.com/MaximeD/gem_updater
> Add changelog_uri to gemspec

- lib/active_storage/service/cloudinary_service.rb
- spec/account_api_spec.rb
- spec/active_storage/database/setup.rb
- spec/active_storage/service/cloudinary_service_spec.rb
- spec/spec_helper.rb
> Fix ActiveStorage type detection for email files

- cloudinary.gemspec
The following warning is thrown with Ruby 3.3.5:
```
ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Also please contact the author of cloudinary-2.1.2 to request adding ostruct into its gemspec.
> Fix Ruby 3.3.5 ostruct warning

- lib/cloudinary/api.rb
- spec/api_spec.rb
- spec/metadata_spec.rb
> Add support for `allow_dynamic_list_values` parameter in `MetadataField`

- lib/cloudinary/helper.rb
Adds an optional parameter to the `cloudinary_js_config` helper method to allow passing additional options through to add to the `<script>` tag.
Specifically, this allows passing through a nonce so that the tag can be compatible with a nonce-based `Content-Security-Policy` header, e.g.:
```
<%= cloudinary_js_config nonce: content_security_policy_nonce %>
```
> Allow passing tag options/attributes for cloudinary_js_config

- lib/cloudinary/carrier_wave/process.rb
- lib/cloudinary/carrier_wave/storage.rb
- spec/carriewave_spec.rb
> Add support for providing upload parameters in CarrierWave
